<div class="container mt-3">

  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3"><?php echo $this->titulo; ?> </h1>
      <h2><?php echo $this->subtitulo; ?></h2>
      <br />

      <?php if (isset($this->mensagem_error)) : ?>
        <div class="alert alert-danger" role="alert" id="msgerror"><?php echo $this->mensagem_error; ?></div>

      <?php endif; ?>

      <?php if (isset($this->mensagem)) : ?>
        <div class="alert alert-success" role="alert" id="msgsucesso"><?php echo $this->mensagem; ?></div>

      <?php endif; ?>

      <?php if (isset($this->_error)) : ?>

        <div class="alert alert-danger" role="alert" id="msgerror"><?php echo $this->_error; ?></div>

      <?php endif; ?>


      <br />
      <a class="btn btn-primary btn-lg" href="<?php echo BASE_URL; ?> " role="button"><i class="bi bi-house"></i> Início</a>
      <a class="btn btn-info btn-lg my-3 " href="javascript:history.back()" role="button"><i class="bi bi-chevron-compact-left"></i> Voltar</a>
      <?php if (!Session::get('autenticado')) :  ?>

        <a class="btn btn-danger btn-lg" href="<?php echo BASE_URL . 'login'; ?> " role="button"><i class="bi bi-chevron-bar-right"></i> Iniciar Sessão</a>

      <?php endif; ?>

    </div>
  </div>

</div>