
<div class="container">

<div class="jumbotron">
        <div class="container">
        <h1 class="display-3"><?php echo $this->titulo; ?> </h1>
        <h2><?php echo $this->subtitulo; ?></h2>
          <br/>
         <div class="alert alert-danger" role="alert" id="error"><?php if (isset($this->mensagem)) { echo $this->mensagem; } ?></div>
         <br/>  
          <a class="btn btn-primary btn-lg" href="<?php echo BASE_URL; ?> " role="button"><i class="bi bi-chevron-compact-left"></i>Início</a>
          <a class="btn btn-info btn-lg my-3" href="javascript:history.back()" role="button"><i class="bi bi-chevron-compact-left"></i> Voltar</a>
           
        </div>
      </div>

</div>

<?php ?>