
<div class="container">

<div class="jumbotron">
        <div class="container">
        <h1 class="display-3"><?php if(isset($this->titulo)) {echo $this->titulo;} ?> </h1>
        <h2><?php if(isset($this->subtitulo)) {echo $this->subtitulo;} ?></h2>
          <br/>
          <a class="btn btn-primary btn-lg" href="<?php echo BASE_URL; ?> " role="button"><i class="bi bi-house"></i> Início</a>
          <?php if (!Session::get('autenticado')) :  ?>
            
          <a class="btn btn-danger btn-lg" href="<?php echo BASE_URL.'login'; ?> " role="button"><i class="bi bi-chevron-bar-right"></i> Iniciar Sessão</a>
          
          <?php endif; ?>
           
        </div>
      </div>

</div>